version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    env_file: .env
    environment:
      DJANGO_SETTINGS_MODULE: openmoxie.settings
      STT_URL: http://stt:8001/stt
      OLLAMA_HOST: http://ollama:11434
      LLM_PROVIDER: ollama
      OLLAMA_MODEL: llama3.2:3b
      STT_BACKEND: local
      STT_LANG: en
      MQTT_HOST: mqtt
      MQTT_PORT: "8883"
    ports:
      - "8000:8000"
    volumes:
      - ./site/work:/app/site/work
      - ./site/static:/app/site/static
    depends_on:
      - mqtt
      - stt
      - ollama
    restart: unless-stopped

  stt:
    build:
      context: .
      dockerfile: stt.Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./site/services/stt/models:/models:ro
    environment:
      STT_MODEL: /models/faster-whisper-small.en
      STT_DEVICE: "auto"
      STT_COMPUTE: "int8"
      STT_VAD: "1"
    restart: unless-stopped
    # GPU (optional):
    # gpus: all

  mqtt:
    build:
      context: .
      dockerfile: mqtt.Dockerfile
    ports:
      - "8883:8883"
    volumes:
      - ./keys:/keys:ro
      - ./local/work:/work
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped
    # GPU (optional):
    # gpus: all

volumes:
  ollama:
